@startuml
left to right direction
legend top left
    |Цвет| Приоритет |
    |<#palegreen>| Must|
    |<#Khaki>| Should |
    |<#LightSkyBlue>| Could |
endlegend
skinparam defaultFontSize 15

actor Пользователь as user
actor Куратор as curator
actor "Облачное хранилище" as cloud_storage

rectangle Система {
  rectangle "Общие Use Cases" {
    usecase (Войти в систему) as login #palegreen
    usecase (Просмотреть курс) as watch_course #palegreen
    usecase (Создать проект) as create_project #LightSkyBlue
    usecase (Оценить проект) as grade_project #LightSkyBlue
    usecase (Выложить документ) as create_document #LightSkyBlue
  }

  usecase (Оставить решение на задание) as solve_task #LightSkyBlue
  usecase (Оставить комментарий) as set_comment #LightSkyBlue
  usecase (Выложить курс в систему) as create_course #palegreen
  usecase (Проверить задание) as check_task #Khaki

  user --> solve_task

  curator --> create_course
  curator --> check_task

  login <.. user
  login <.. curator

  watch_course <.. user
  watch_course <.. curator

  create_project <.. user
  create_project <.. curator

  grade_project <.. user
  grade_project <.. curator

  create_document <.. user
  create_document <.. curator

  create_course -> cloud_storage
  watch_course -> cloud_storage

  watch_course <.. set_comment : расширить
  grade_project <.. set_comment : расширить
  solve_task <.. set_comment : расширить
  create_document <.. set_comment : расширить
}

@enduml
