CREATE TABLE users (
    users_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    chat_id BIGINT UNIQUE,
    PRIMARY KEY (users_id)
);


CREATE TABLE url (
    url_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    url VARCHAR(200) NOT NULL,
    link_type VARCHAR(13) CHECK (link_type IN ('GITHUB', 'STACKOVERFLOW')),
    PRIMARY KEY (url_id)
);

CREATE TABLE link (
    link_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    users_id BIGINT,
    url_id BIGINT,
    PRIMARY KEY (link_id),
    FOREIGN KEY (users_id) REFERENCES users(users_id) ON DELETE CASCADE,
    FOREIGN KEY (url_id) REFERENCES url(url_id) ON DELETE CASCADE
);

CREATE TABLE content (
    content_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    answer TEXT,
    creation_time VARCHAR(100),
    title VARCHAR(256),
    updated_type VARCHAR(7) CHECK (updated_type IN ('COMMENT', 'ANSWER', 'PR', 'ISSUE')),
    user_name VARCHAR(100),
    url_id BIGINT,
    PRIMARY KEY (content_id),
    FOREIGN KEY (url_id) REFERENCES url(url_id) ON DELETE CASCADE
);

CREATE TABLE link_filters (
    link_id BIGINT NOT NULL,
    filters TEXT,
    FOREIGN KEY (link_id) REFERENCES link(link_id) ON DELETE CASCADE
);

CREATE TABLE link_tags (
    link_id BIGINT NOT NULL,
    tags TEXT,
    FOREIGN KEY (link_id) REFERENCES link(link_id) ON DELETE CASCADE
);

create index url_hash_idx on url using hash (url);
create index url_chat_id_idx on users using hash (chat_id)
