CREATE SCHEMA IF NOT EXISTS scrapper;

-- Пользователи
CREATE TABLE scrapper.user (
    chat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

-- URL
CREATE TABLE scrapper.url (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(200) NOT NULL,
    link_type VARCHAR(13) CHECK (link_type IN ('GITHUB', 'STACKOVERFLOW')),
    UNIQUE(url)  -- Уникальность URL
);

-- Основная таблица связи пользователя и URL
CREATE TABLE scrapper.link (
    user_id BIGINT NOT NULL,
    url_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, url_id),
    FOREIGN KEY (user_id) REFERENCES scrapper.user(chat_id) ON DELETE CASCADE,
    FOREIGN KEY (url_id) REFERENCES scrapper.url(id) ON DELETE CASCADE
);

-- Таблица тегов (много тегов на одну пару user_id+url_id)
CREATE TABLE scrapper.link_tags (
    user_id BIGINT NOT NULL,
    url_id BIGINT NOT NULL,
    tag TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES scrapper.user(chat_id) ON DELETE CASCADE,
    FOREIGN KEY (url_id) REFERENCES scrapper.url(id) ON DELETE CASCADE
);

-- Таблица фильтров (теперь аналогична таблице тегов)
CREATE TABLE scrapper.link_filters (
    user_id BIGINT NOT NULL,
    url_id BIGINT NOT NULL,
    filter TEXT NOT NULL,  -- Просто текст фильтра (без типа)
    FOREIGN KEY (user_id) REFERENCES scrapper.user(chat_id) ON DELETE CASCADE,
    FOREIGN KEY (url_id) REFERENCES scrapper.url(id) ON DELETE CASCADE
);


CREATE TABLE scrapper.content (
    id BIGSERIAL PRIMARY KEY,
    answer TEXT,
    creation_time TEXT,
    title TEXT,
    user_name TEXT,
    url_id BIGINT,
    FOREIGN KEY (url_id) REFERENCES scrapper.url(id) on DELETE CASCADE
);

CREATE TABLE scrapper.github_content (
    id BIGINT PRIMARY KEY,
    updated_type VARCHAR(5) CHECK (updated_type IN ('PR', 'ISSUE')),
    FOREIGN KEY (id) REFERENCES scrapper.content(id) ON DELETE CASCADE
);

CREATE TABLE scrapper.stackoverflow_content (
    id BIGINT PRIMARY KEY,
    updated_type VARCHAR(7) CHECK (updated_type IN ('COMMENT', 'ANSWER')),
    FOREIGN KEY (id) REFERENCES scrapper.content(id) ON DELETE CASCADE
);

-- Индексы
CREATE INDEX url_hash_idx ON scrapper.url USING hash (url);
